export const STRIPE_PRICES = {
  starter: {
    monthly: 'price_1TKlhIIjaYaM2IiLfPfayAFs',
    yearly:  'price_1TKlhIIjaYaM2IiLfPfayAFs',
  },
  growth: {
    monthly: 'price_1TKlhIIjaYaM2IiLfPfayAFs',
    yearly:  'price_1TKlhIIjaYaM2IiLfPfayAFs',
  },
} as const

export const PLANS = {
  free: {
    name: 'Free',
    price: { monthly: 0, yearly: 0 },
    experiments: 1,
    impressionsPerMonth: 250,
    workspaces: 1,
    multivariate: false,
    webhooks: false,
    whiteLabel: false,
    analyticsDestinations: [] as string[],
    showBranding: true,
    supportLevel: 'none',
    stripePrices: null,
  },
  starter: {
    name: 'Starter',
    price: { monthly: 29, yearly: 290 },
    experiments: 3,
    impressionsPerMonth: 5_000,
    workspaces: 3,
    multivariate: false,
    webhooks: false,
    whiteLabel: false,
    analyticsDestinations: ['ga4', 'plausible'],
    showBranding: false,
    supportLevel: 'email',
    stripePrices: STRIPE_PRICES.starter,
  },
  growth: {
    name: 'Growth',
    price: { monthly: 79, yearly: 790 },
    experiments: 10,
    impressionsPerMonth: 50_000,
    workspaces: 10,
    multivariate: true,
    webhooks: true,
    whiteLabel: false,
    analyticsDestinations: ['ga4', 'posthog', 'plausible', 'mixpanel', 'amplitude', 'webhook'],
    showBranding: false,
    supportLevel: 'email',
    stripePrices: STRIPE_PRICES.growth,
  },
  scale: {
    name: 'Scale',
    price: { monthly: 0, yearly: 0 },
    experiments: Infinity,
    impressionsPerMonth: Infinity,
    workspaces: Infinity,
    multivariate: true,
    webhooks: true,
    whiteLabel: true,
    analyticsDestinations: ['ga4', 'posthog', 'plausible', 'mixpanel', 'amplitude', 'webhook'],
    showBranding: false,
    supportLevel: 'priority',
    stripePrices: null,
  },
} as const

export type PlanKey = keyof typeof PLANS
