export const PLANS = {
  free: {
    name: 'Free',
    price: 0,
    experiments: 1,
    visitsPerMonth: 500,
    workspaces: 1,
    ga4Integration: false,
    multivariate: false,
    webhooks: false,
    whiteLabel: false,
    analyticsDestinations: [],
    showBranding: true,
    supportLevel: 'none',
  },
  starter: {
    name: 'Starter',
    price: 29,
    experiments: 3,
    visitsPerMonth: 50_000,
    workspaces: 1,
    ga4Integration: true,
    multivariate: false,
    webhooks: false,
    whiteLabel: false,
    analyticsDestinations: ['ga4', 'plausible'],
    showBranding: false,
    supportLevel: 'email',
  },
  growth: {
    name: 'Growth',
    price: 79,
    experiments: 10,
    visitsPerMonth: 500_000,
    workspaces: 3,
    ga4Integration: true,
    multivariate: true,
    webhooks: true,
    whiteLabel: false,
    analyticsDestinations: ['ga4', 'posthog', 'plausible', 'mixpanel', 'amplitude', 'webhook'],
    showBranding: false,
    supportLevel: 'email',
  },
  agency: {
    name: 'Agency',
    price: 199,
    experiments: Infinity,
    visitsPerMonth: 5_000_000,
    workspaces: Infinity,
    ga4Integration: true,
    multivariate: true,
    webhooks: true,
    whiteLabel: true,
    analyticsDestinations: ['ga4', 'posthog', 'plausible', 'mixpanel', 'amplitude', 'segment', 'rudderstack', 'webhook'],
    showBranding: false,
    supportLevel: 'priority',
  },
  enterprise: {
    name: 'Enterprise',
    price: null,
    experiments: Infinity,
    visitsPerMonth: Infinity,
    workspaces: Infinity,
    ga4Integration: true,
    multivariate: true,
    webhooks: true,
    whiteLabel: true,
    analyticsDestinations: ['all'],
    sso: true,
    sla: true,
    showBranding: false,
    supportLevel: 'dedicated',
  },
} as const

export type PlanKey = keyof typeof PLANS
