packages:
  - 'app'
  - 'worker'
  - 'plugin'
  - 'plugin/packages/*'
  - 'astro-demo-internal'
allowBuilds:
  '@parcel/watcher': false
  better-sqlite3: true
  esbuild: true
  sharp: false
  workerd: true
